services:
  verdaccio:
    image: verdaccio/verdaccio:5
    ports:
      - "4873:4873"
    volumes:
      - ./verdaccio-storage:/verdaccio/storage
      - ./verdaccio.yaml:/verdaccio/conf/config.yaml
    networks:
      - grpc-network
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:4873/', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) }).on('error', () => process.exit(1))",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  grpc-network:
    name: grpc-dev-network
    external: true
