name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  validate:
    name: Validate (${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x, 22.x]
      fail-fast: false
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq protobuf-compiler
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run preflight checks
        run: ./cli/lab preflight
        env:
          CI: true
          TERM: xterm-256color
          
      - name: Upload failure logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failure-logs-${{ matrix.node-version }}
          path: |
            npm-debug.log
            **/npm-debug.log
            **/*.log
          retention-days: 7

  ci-status:
    name: CI Status
    runs-on: ubuntu-latest
    needs: [validate]
    if: always()
    steps:
      - name: Check CI Status
        run: |
          # Check if all required jobs succeeded
          if [[ "${{ needs.validate.result }}" == "success" ]]; then
            echo "✅ All CI checks passed"
            exit 0
          else
            echo "❌ CI checks failed - validate: ${{ needs.validate.result }}"
            exit 1
          fi