name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  validate:
    name: Validate (${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
      fail-fast: false
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
      
      - name: Install dependencies
        run: |
          # Install root dependencies
          npm ci
          
          # Install dependencies for each package with verify scripts
          find . -name "package.json" -not -path "*/node_modules/*" -exec dirname {} \; | while read dir; do
            if [ "$dir" != "." ] && jq -e '.scripts.verify' "$dir/package.json" >/dev/null 2>&1; then
              echo "Installing dependencies for $dir"
              (cd "$dir" && npm ci)
            fi
          done
      
      - name: Run preflight checks
        run: ./cli/lab preflight
        env:
          CI: true
          TERM: xterm-256color
          
      - name: Upload failure logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failure-logs-${{ matrix.node-version }}
          path: |
            npm-debug.log
            **/npm-debug.log
            **/*.log
          retention-days: 7